export const state = {
    grid: [],
    horde: [],
    spawnPoint: null,
    flagPosition: null,
    currentMap: null,
    activeFormation: 'none',
    targetDestination: null,
    gamePaused: false,
    globalWindMultiplier: 1.0,
    isDragging: false,
    time: 0,
    startTime: 0,
    score: 0,
    venturiEnabled: true,
    victoryZoneSize: 2,
    windParams: {},
    selectionRect: { startX: 0, startY: 0, currentX: 0, currentY: 0 },
};